// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Greeting struct {
	Message string `json:"message"`
}

type NewTemplate struct {
	Hello  *string `json:"hello"`
	Suffix *string `json:"suffix"`
}

type Template struct {
	Hello  string `json:"hello"`
	Suffix string `json:"suffix"`
}
